apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ecommerce-data
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: ecommerce-mysql:init
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: ecommerceproducts
            - name: MYSQL_USER
              value: ecommerce
            - name: MYSQL_PASSWORD
              value: admin
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-padmin"]
            initialDelaySeconds: 20
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecommerce-data
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
