apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: ecommerce-users-api:aks-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__PostgresConnection
              value: Host=postgres.ecommerce-data.svc.cluster.local;Port=5432;Database=eCommerceUsers;Username=postgres;Password=123
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: ecommerce
spec:
  selector:
    app: users-api
  ports:
    - port: 80
      targetPort: 8080
